### ISSUE TITLE
The basic example just don't work

### ISSUE THREAD

**Issue by vinyll** [bielcardona/PhyloNetworks#6]
Running a basic example from the doc returns

```
network.descendant_nodes('_2')

TypeError: list() takes at most 1 argument (2 given)
```

**Comment by bielcardona** [comment]
I was adapting the library to python 3, and uploaded the new version before testing it (my fault!). I hope to have a new version available by the end this week.
Thanks for letting me know!

**Comment by vinyll** [comment]
Not sure what is going on here.
I guess it would be better to have an open issue with a PR exposing the current limit than just ignoring this point :/

**Comment by bielcardona** [comment]
I thought it was left open by error... Did you try it with the last version?

**Comment by vinyll** [comment]
Actually I can't find the "basic example" that we mentioned.
The tests are passing and seem to match a basic feature (suggestion: having the test with a verbose name)
LGFM 👌
